language: generic

services:
  - docker
  
before_install:
  - chmod +x run-app.sh
  - chmod +x push-app.sh
script:
  - ./run-app.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./push-app.sh
