version: '3.4'

services:
  eventstore:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event-store-db
    volumes:
      - database_data:/var/lib/postgresql/data 
    networks:
      - eventsource-network

  eventsource.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EventStore__ConnectionString=PORT = 5432; HOST = eventstore; TIMEOUT = 15; POOLING = True; MINPOOLSIZE = 1; MAXPOOLSIZE = 100; COMMANDTIMEOUT = 20; DATABASE = 'event-store-db'; PASSWORD = 'postgres'; USER ID = 'postgres'
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - eventsource-network
    depends_on:
      - eventstore

networks:
  eventsource-network:

volumes:
  database_data:
    driver: local