version: '3.4'

services:
  eventstore:
    container_name: eventstore
    image: postgres:9.5

  eventsource.api:
    container_name: eventsourceapi
    image: profjordanov/eventsourceapi:latest
    build:
      context: .
      dockerfile: EventSource.Api/Dockerfile